Repository laminas/laminas-cache-storage-adapter-redis, pull requests merged in 2022-12, with the labels that each got.

#53 fix: Use exception message if `$redis->getLastError()` returns null
  psalm-baseline.xml
  src/Redis.php
Labels: Bug

#68 PHP 8.2: Remove dynamic property creation in unit test
  test/integration/Laminas/RedisFromExtensionAsset.php
  test/integration/Laminas/RedisTest.php
Labels: Enhancement

#69 Handle `RedisException` in `RedisResourceManager`
  psalm-baseline.xml
  psalm.xml
  src/Exception/RedisRuntimeException.php
  src/RedisCluster.php
  src/RedisClusterResourceManager.php
  src/RedisResourceManager.php
  test/integration/Psr/CacheItemPool/RedisClusterWithPhpIgbinaryTest.php
  test/integration/Psr/CacheItemPool/RedisClusterWithPhpSerializeTest.php
  test/integration/Psr/CacheItemPool/RedisClusterWithoutSerializerTest.php
  test/integration/Psr/CacheItemPool/RedisIntegrationTest.php
  test/unit/RedisClusterOptionsTest.php
  test/unit/RedisResourceManagerTest.php
Labels: Bug, Enhancement

#61 Drop PHP 7.4 support, upgrade to vimeo/psalm v5
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Exception/RedisRuntimeException.php
  src/Redis.php
  src/RedisCluster.php
  src/RedisClusterOptions.php
  src/RedisResourceManager.php
  test/integration/Laminas/RedisTest.php
Labels: Enhancement, dependency update
